### ISSUE TITLE
"Unable to create a timer, the lua context does not have a timer world"

### ISSUE THREAD

**Issue by 8bitskull** [heroiclabs/nakama-defold#11]
I'm in the process of making a test project to get to grips with Nakama in Defold.

When using nakama.create_socket() I get the following error:

ERROR:SCRIPT: Unable to create a timer, the lua context does not have a timer world

I believe this is ultimately triggered by: https://github.com/heroiclabs/nakama-defold/blob/master/nakama/engine/defold.lua#L95

There is no reference to timer in nakama.create_socket(), but the function does call create_socket() in the Defold engine module.

**Comment by britzl** [comment]
Are you calling `nakama.create_socket()` **many** times and run out of resources?

Have you added the dependencies? https://github.com/heroiclabs/nakama-defold#getting-started

**Comment by 8bitskull** [comment]
No, I am calling it only once. I have a fresh project based on the Defold desktop project template. The only thing I have done is add the dependencies (see below) and added a script. This is the entirety of the script:

```
local defold = require "nakama.engine.defold"
local nakama = require "nakama.nakama"
local config = {
	host = "127.0.0.1",
    port = 7350,
    use_ssl = false,
    username = "defaultkey",
    password = "",
	engine = defold,
}
local client = nakama.create_client(config)
local socket = nakama.create_socket(client)
```

This is basically just a copy of the [Getting started](https://github.com/heroiclabs/nakama-defold#getting-started) section plus one line to create a socket.

Yes on the dependencies:
![image](https://user-images.githubusercontent.com/24439991/88176567-647a2380-cc1f-11ea-8d5a-2c33aa4484c8.png)

**Comment by britzl** [comment]
Are you calling this from init() ?

**Comment by 8bitskull** [comment]
...Nope, I wasn't. I didn't realise that timer (and probably everything else!) was _initialised_ during init() but of course that makes sense. Thanks for the help.
