### ISSUE TITLE
HTML5 build auto disconnect when call socket_send

### ISSUE THREAD

**Issue by hungluongkong** [heroiclabs/nakama-defold#13]
Hi there,

I have cloned this and run the example.
(To build HTML5, I removed `codegen` folder. and no change anything)
When build and run HTML5, I got `Disconnected` when call socket_send
```lua
nakama.socket_send(socket, channel_join_message)
```
You can see log here: https://anotepad.com/note/read/94xi4wqj
Could you please take a look for this?

**Comment by britzl** [comment]
We have replaced the old Lua based WebSocket implementation from the initial release of Nakama-Defold with a new native WebSocket extension (see #20). This issue is resolved through the upgrade to the native WebSocket solution.
