### ISSUE TITLE
Error when using client functions with uri_encode "attempt to call global 'uri_encode' (a nil value)"

### ISSUE THREAD

**Issue by laimonasr** [heroiclabs/nakama-defold#14]
Hi when calling any function of the client that uses uri_encode I get this error `/nakama/nakama.lua:3296: attempt to call global 'uri_encode' (a nil value)` (rpc_func(...) in this case). Seems like uri_encode is missing within the scope of the client.

Discussion on gitter regarding this https://gitter.im/heroiclabs/nakama?at=5f932453eb82301c1a451c88

**Comment by novabyte** [comment]
Fixed in https://github.com/heroiclabs/nakama-defold/commit/40c867f96e041a1cbab094eedd7862f40e45eb60.
