### ISSUE TITLE
Authentication errors raise exceptions

### ISSUE THREAD

**Issue by uncleNight** [heroiclabs/nakama-defold#23]
Hi guys,

Started implementing user logins with custom usernames, needed to validate existing usernames, stumbled upon this:
```
DEBUG:SCRIPT: init()
DEBUG:SCRIPT: authenticate_device() with coroutine
DEBUG:SCRIPT: HTTP	POST	http://192.168.0.234:1750/v2/account/authenticate/device?create=true&username=Test
DEBUG:SCRIPT: DATA	{"id":"81a40de2-134c-4e82-ceb4-68545ab2cb63"}
DEBUG:SCRIPT: {"code":6,"message":"Username is already in use."}
ERROR:SCRIPT: /nakama/session.lua:17: You must provide a token
stack traceback:
  [C]:-1: in function assert
  /nakama/session.lua:17: in function create
  /nakama/nakama.lua:1756: in function callback
  /nakama/engine/defold.lua:74: in function </nakama/engine/defold.lua:68>
```
without debug enabled it just looks like an out-of-nowhere error although what I'm supposed to get is `Username is already in use` as a message returned.

Here, the response that the client gets from the server actually looks like this:
```
{
  status = 409,
  response = "{"code":6,"message":"Username is already in use."}",
  headers = {
    date = "Wed, 03 Feb 2021 19:41:38 GMT",
    content-length = "50",
    content-type = "application/json",
    cache-control = "no-store, no-cache, must-revalidate"
  }
}
```

but in the code (`nakama/nakama.lua:1755`) the client doesn't check for HTTP status code and relies on `result.error` property of the response (which is absent in the message):

```lua
return async(function(done)
    client.engine.http(client.config, url_path, query_params, "POST", post_data, function(result)
        if not result.error and api_session then 
            result = api_session.create(result)
        end
        done(result)
    end)
end)
```

Pretty much the same code is used across all the `authenticate_*` functions which means server responses like this one throw exceptions instead.

I believe the client should rely on the HTTP status code to determine if the response actually makes sense to continue authentication - plus, 409 is not the most common HTTP code which means Nakama devs are actually following the RFCs so the server responding with 200 or 201 is to be expected if the authentication has succeeded.

**Comment by britzl** [comment]
This is a good catch! We should indeed accept response codes >= 200 and < 300 as OK and treat anything >= 400 as an error.

@novabyte Anything to add here?

**Comment by novabyte** [comment]
@britzl It's a good spot by @uncleNight. I think we'd want to check in a similar pattern to the .NET client:

https://github.com/heroiclabs/nakama-dotnet/blob/master/src/Nakama/HttpRequestAdapter.cs#L84-L99

Essentially the steps are:

1. Check if the response status code is 400 or above. This needs to be handled as an error handler code path.
2. If the code is in a range of errors that can be decoded (i.e. bad request, etc) then decode the additional error info. I think the client already does this.
3. If the status code is beyond a range that could be decoded with more info we can only surface the raw data if any and the http status code to help.
