### ISSUE TITLE
Problem with WebSocket connections in HTML5 builds using wss://

### ISSUE THREAD

**Issue by britzl** [heroiclabs/nakama-defold#24]
I'm having problems receiving messages in HTML5 builds using the native WebSocket extension introduced in recent releases of Nakama-Defold.The same works well on desktop.

I'm able to connect to a Nakama Cloud hosted server and I can send a message (a matchmaker_add message), but I never get a response. I see that the socket starts receiving an empty message repeatedly after I send the first message. 

The WebSocket extension can successfully send and receive data in an HTML5 build when connecting to wss://echo.websocket.org.

There's something different with the connection to the Nakama server. Any ideas? @novabyte?

@uncleNight have you successfully connected in an HTML5 build?

**Comment by uncleNight** [comment]
hi @britzl I don't build for HTML5 but I'll have a look when I can.

**Comment by uncleNight** [comment]
Indeed, I can reproduce the same behavior:
```
ERROR:SCRIPT: nakama.util.json:185: unexpected character '' at line 1 col 1 dmloader.js:512:40
stack traceback: dmloader.js:512:40
  [C]:-1: in function error dmloader.js:512:40
  nakama.util.json:185: in function decode_error dmloader.js:512:40
  nakama.util.json:383: in function parse dmloader.js:512:40
  nakama.util.json:391: in function decode dmloader.js:512:40
  nakama.engine.defold:94: in function on_message dmloader.js:512:40
  nakama.engine.defold:135: in function <nakama.engine.defold:123> dmloader.js:512:40
<empty string>
DEBUG: SCRIPT: EVENT_MESSAGE
```

and it goes oooon and on

**Comment by britzl** [comment]
> but then this cryptic thingy happens on Nakama server

This is interesting! I didn't see anything in the server log (but I probably didn't look close enough or not in the right place).

**Comment by britzl** [comment]
There error comes from here:

https://github.com/heroiclabs/nakama/blob/68f8100899412fb8e18f426e92583f5dac7d15f1/server/session_ws.go#L204-L210

**Comment by uncleNight** [comment]
Just came here to say the same - went for `grep`ing source code for the error message.
