### ISSUE TITLE
SDK Updates

### ISSUE THREAD

**Issue by novabyte** [heroiclabs/nakama-defold#28]
We need to investigate what the IAP support in Defold engine looks like as well as introduce the new session refresh APIs to the client object.

**Comment by britzl** [comment]
In-App Purchases for iOS, Android (Google+Amazon) and Facebook are handled in this extension:

https://defold.com/extension-iap/

Basic API is:

```
iap.set_listener(fn)
iap.list(product_ids, fn)
iap.buy()
iap.finish(receipt)
```

What do you need specifically? Is this for receipt validation?

> introduce the new session refresh APIs to the client object

Could you tell me more about this?

---

I can pick up this task later this week or beginning of next.

**Comment by britzl** [comment]
FYI Starting work on this now.

**Comment by novabyte** [comment]
Thanks @britzl 🙏

**Comment by britzl** [comment]
I ran the code generator with the latest API definitions and there was indeed a number of new IAP receipt functions.

I also noticed some changes to linking of Steam accounts.

And the generated code for the "/v2/friend" endpoint has some new arguments (I don't see how the functions could have worked before).

Finally there was also a new "/v2/session/logout" endpoint.

**Comment by britzl** [comment]
PR with the changes: https://github.com/heroiclabs/nakama-defold/pull/29

**Comment by britzl** [comment]
For the IAP purchase validation we need to add some documentation about which Defold extension to include when using In-App Purchase. I don't see any IAP related docs yet though (https://heroiclabs.com/docs/index.html).

**Comment by britzl** [comment]
Oh, here it is: https://heroiclabs.com/docs/iap-validation/

**Comment by britzl** [comment]
Commit to my nakama-docs branch with IAP validation for Defold:

https://github.com/britzl/nakama-docs/commit/1f212c47f973e308cf21dad0ebdf87556f0c1686
