### ISSUE TITLE
3.0.0: nakama/socket.lua:18: attempt to call global 'log' (a nil value)

### ISSUE THREAD

**Issue by logicalparadox** [heroiclabs/nakama-defold#43]
Reproduce by receiving a socket event that does not have a bound listener.

```
ERROR:SCRIPT: nakama/socket.lua:18: attempt to call global 'log' (a nil value)
stack traceback:
  nakama/socket.lua:18: in function on_message
  nakama/engine/defold.lua:122: in function on_message
  nakama/engine/defold.lua:164: in function <nakama/engine/defold.lua:152>
```

**Comment by britzl** [comment]
Thank you for the report @logicalparadox. And sorry about this. I encountered this problem myself and by accident made the fix in the generated code instead of in the template.

In the coming weeks I'll add unit tests to catch issues such as this one.
